server:
  ## 若port不设置值，默认为8188，这个值必须
  port: 8188
  ##应用的访问的根目录
  contextPath: /
  dataPath: data
  pprof: true
  pprofPort: 9123

redis:
  #redis地址
  addrs: ["localhost:6379"]
  #密码
  pwd: ""
  #线程池
  PoolSize: 1000
  #选择库，默认0
  db: 0
  #是否是哨兵模式
  isSentinel: false
  #哨兵模式master name
  masterName: ""
  #哨兵地址
  sentinelAddrs: []

logger:
  #gin模式
  mode: debug
  #日志级别
  level: debug
  #是否写入到文件
  isOutPutFile: false
  #保存期限
  maxAgeDay: 7
  #按天保存
  rotationTime: 1

mongodb:
  hosts: ["127.0.0.1:27017"]
  maxPoolSize: 100
  userName: mongoadmin
  password: secret